# Generated by Django 4.1.1 on 2022-09-28 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date_end",
        ),
        migrations.RemoveField(
            model_name="event",
            name="date_start",
        ),
    ]
